# Generated by Django 6.0.6 on 2026-06-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Units still available in inventory for FIFO consumption.'),
        ),
    ]
