# Generated by Django 6.0.6 on 2026-10-01 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0017_inventory_avg_unit_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'code'], name='product_name_code_idx'),
        ),
    ]
