# Generated by Django 6.0.6 on 2026-07-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(editable=False, help_text='Auto-generated e.g. PAY-2026-0001', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='reference_number',
            field=models.CharField(editable=False, help_text='Auto-generated e.g. RTN-2026-0001', max_length=30, unique=True),
        ),
    ]
