# Generated by Django 6.0.6 on 2026-06-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_grand_total_invoice_gst_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='credit_received',
            new_name='credit_outstanding',
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa'), ('bank', 'Bank Transfer')], max_length=12),
        ),
    ]
