import uuid

from django.conf import settings
from django.db import models
from django.utils import timezone


class PartnerRateAccess(models.Model):
    """
    One row per partner software that has asked to see this software's rate
    list. The partner_name is the caller's COMPANY_NAME, and only names that
    exist in B2B_PARTNER_SECRETS can ever create a row, so the table stays
    as small as the number of partner softwares.

    Rows are never deleted — a withdrawn share is status=REVOKED, which keeps
    the history and lets the partner request again.
    """

    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        APPROVED = "approved", "Approved"
        REJECTED = "rejected", "Rejected"
        REVOKED = "revoked", "Sharing stopped"

    partner_name = models.CharField(max_length=255, unique=True)
    status = models.CharField(
        max_length=10, choices=Status.choices, default=Status.PENDING, db_index=True,
    )
    # Time of the latest (re-)request — the approval list is newest-first on this.
    requested_at = models.DateTimeField(default=timezone.now, db_index=True)
    status_changed_at = models.DateTimeField(default=timezone.now)
    decided_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )

    class Meta:
        verbose_name = "Partner Rate Access"
        verbose_name_plural = "Partner Rate Accesses"
        ordering = ["-requested_at"]

    def __str__(self):
        return f"{self.partner_name} — {self.status}"


class PartnerRateAccessEvent(models.Model):
    """Audit trail: every status change of a PartnerRateAccess, newest last."""

    access = models.ForeignKey(
        PartnerRateAccess, on_delete=models.PROTECT, related_name="events",
    )
    from_status = models.CharField(max_length=10, blank=True)
    to_status = models.CharField(max_length=10)
    # Null when the partner itself triggered the change (a request / re-request).
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["at", "id"]

    def __str__(self):
        return f"{self.access.partner_name}: {self.from_status or '-'} -> {self.to_status}"


# ---------------------------------------------------------------------------
# Purchase requests (a partner software asks to buy from this one)
# ---------------------------------------------------------------------------

class PurchaseRequest(models.Model):
    """
    A partner's request to buy items from this software. One row per request;
    never deleted — a cancelled request is simply hidden from the admin list.

    The partner's own shelf choices are NEVER sent here, so nothing about
    them exists in this table. The shelves this software picks live on the
    invoice it creates when accepting.
    """

    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        ACCEPTED = "accepted", "Accepted"
        DENIED = "denied", "Denied"
        CANCELLED = "cancelled", "Cancelled"

    partner_name = models.CharField(max_length=255)
    # Generated by the partner; makes a re-sent submit a no-op.
    request_uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.PENDING)
    note = models.CharField(max_length=500, blank=True, default="")
    requested_at = models.DateTimeField(default=timezone.now, db_index=True)
    decided_at = models.DateTimeField(null=True, blank=True)
    decided_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name="+",
    )
    # The confirmed invoice created on accept (null until then).
    invoice = models.OneToOneField(
        "billing.Invoice", null=True, blank=True,
        on_delete=models.PROTECT, related_name="b2b_purchase_request",
    )
    invoice_number = models.CharField(max_length=30, blank=True, default="")

    class Meta:
        verbose_name = "Purchase Request"
        verbose_name_plural = "Purchase Requests"
        ordering = ["-requested_at"]
        constraints = [
            models.UniqueConstraint(fields=["partner_name", "request_uuid"], name="b2b_request_partner_uuid_uniq"),
        ]
        indexes = [
            # The admin list: filter by status, newest first.
            models.Index(fields=["status", "-requested_at"], name="b2b_request_status_time_idx"),
        ]

    def __str__(self):
        return f"{self.partner_name} — {self.request_uuid} ({self.status})"


class PurchaseRequestItem(models.Model):
    request = models.ForeignKey(PurchaseRequest, on_delete=models.PROTECT, related_name="items")
    product = models.ForeignKey("purchases.Product", on_delete=models.PROTECT, related_name="+")
    # Snapshots, so the record stays readable if the product is later renamed.
    product_code = models.CharField(max_length=100)
    product_name = models.CharField(max_length=255)
    requested_quantity = models.PositiveIntegerField()
    # Null until decided; 0 means "not supplied".
    accepted_quantity = models.PositiveIntegerField(null=True, blank=True)
    # Exactly as the partner entered them — the admin cannot change these.
    discount = models.DecimalField(max_digits=10, decimal_places=4, default=0)
    gst = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    wht = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    # Snapshotted from the confirmed invoice line on accept.
    selling_price = models.DecimalField(max_digits=14, decimal_places=4, null=True, blank=True)
    effective_price = models.DecimalField(max_digits=14, decimal_places=4, null=True, blank=True)

    class Meta:
        ordering = ["id"]
        constraints = [
            models.UniqueConstraint(fields=["request", "product"], name="b2b_request_item_product_uniq"),
        ]

    def __str__(self):
        return f"{self.product_code} x {self.requested_quantity}"
