# Generated by Django 6.0.6 on 2026-10-06 02:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
        ('billing', '0012_fifoledger_reverses'),
        ('purchases', '0018_product_product_name_code_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255)),
                ('request_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=30)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='b2b_purchase_request', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('requested_quantity', models.PositiveIntegerField()),
                ('accepted_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('wht', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('effective_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='purchases.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='b2b.purchaserequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', '-requested_at'], name='b2b_request_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.UniqueConstraint(fields=('partner_name', 'request_uuid'), name='b2b_request_partner_uuid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestitem',
            constraint=models.UniqueConstraint(fields=('request', 'product'), name='b2b_request_item_product_uniq'),
        ),
    ]
