# Generated by Django 6.0.6 on 2026-07-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='total_invoices_cash',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total cash ever collected from invoice payments (gross, never reduced).', max_digits=20),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='total_purchases_cash',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total purchase value: paid + outstanding.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='cash_in_hand',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Actual cash available: invoice receipts - expenses - supplier payments.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='customer_outstanding',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Amount customers still owe us.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='supplier_payable_outstanding',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Amount we still owe suppliers.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='total_paid_payables',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total cash ever paid to suppliers.', max_digits=20),
        ),
    ]
